spring:
    application:      name: testclientapp
    profiles:
      active: "dev"
      
---
spring:
  profiles: dev
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
server:  port: 9091
  servlet:    context-path: /testclient
user-service:
  baseUrl: http://localhost:9090/test

---
spring:
  profiles: test
logging:
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
server:
  port: 9091
  servlet:
    context-path: /testclient
user-service:
  baseUrl: http://localhost:9090/test 
